pool: Default

trigger:
- main

steps:
- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --username ido1993ziv@outlook.com --password idoziv12
      az group deployment create --resource-group IdoTask --template-file storageAccountTemplate.json --parameters storageAccountName=storageAccount1 location=<your-location> accountType=Standard_LRS
      az group deployment create --resource-group IdoTask --template-file storageAccountTemplate.json --parameters storageAccountName=storageAccount2 location=<your-location> accountType=Standard_LRS
      az group deployment create --resource-group IdoTask --template-file windowsServerTemplate.json --parameters adminUsername=idoAdmin adminPassword=P@ssw0rd123 vmName=testVm