pool: Default

trigger:
- main

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '<your-subscription-id>'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --username ido1993ziv@outlook.com --password idoziv12
      az account set --subscription a8108c2b-496c-424d-8347-ecc8afb6384c
      az deployment group create --resource-group IdoTask --template-file storageAccountTemplate.json --parameters storageAccountName=storageAccount1 location=eastus accountType=Standard_LRS
      az deployment group create --resource-group IdoTask --template-file storageAccountTemplate.json --parameters storageAccountName=storageAccount2 location=eastus accountType=Standard_LRS
      az deployment group create --resource-group IdoTask --template-file windowsServerTemplate.json --parameters adminUsername=idoAdmin adminPassword=P@ssw0rd123 vmName=testVm