trigger:
- master

pool:
- vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'a8108c2b-496c-424d-8347-ecc8afb6384c'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group deployment create --resource-group IdoTask --template-file storageAccountTemplate.json --parameters storageAccountName=storageAccount1 location=eastus accountType=Standard_LRS
      az group deployment create --resource-group IdoTask --template-file storageAccountTemplate.json --parameters storageAccountName=storageAccount2 location=eastus accountType=Standard_LRS
      az group deployment create --resource-group IdoTask --template-file windowsServerTemplate.json --parameters adminUsername=idoAdmin adminPassword=P@ssw0rd123 vmName=testVm
